name: noorsports_analytics
version: "1.0.0"
config-version: 2

profile: noorsports_analytics

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  noorsports_analytics:
    +materialized: view
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
