noorsports_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('WAREHOUSE_HOST', 'warehouse') }}"
      user: "{{ env_var('WAREHOUSE_USER', 'warehouse') }}"
      password: "{{ env_var('WAREHOUSE_PASSWORD', 'warehouse') }}"
      port: "{{ env_var('WAREHOUSE_PORT', '5432') | int }}"
      dbname: "{{ env_var('WAREHOUSE_DB', 'noorsports') }}"
      schema: public
      threads: 4
